# mkdocs.yml

# -------------------------------------------------------------
# CONFIGURACIÓN GENERAL DEL SITIO
# -------------------------------------------------------------
site_name: PPS-Unidad2-TareaRA2-Aguado-Hernandez-Naiara # Define el título que aparecerá en la barra de navegación y en la etiqueta <title> del navegador.

# -------------------------------------------------------------
# ESTRUCTURA DE NAVEGACIÓN (MENÚ)
# -------------------------------------------------------------
# Define la lista de enlaces y el orden de aparición en el menú de navegación principal.
nav:
  # El nombre de la sección en el menú: nombre_archivo.md
  - Inicio: README.md
  - Apartado 1 - Trazado de vulnerabilidad: TrazadoVulnerabilidadGoAnywhere.md   # o el nombre exacto que tengas
  - Apartado 2 - Análisis de vulnerabilidad: analisisVulnerabilidad.md
  - Apartado 3 - Comprobación requisitos: ComprobacionRequisitosAplicacion_naiara.md
  - Apartado 4 - Reflexión: reflexion.md
  # - Referencia: 
  #   - Funciones: referencia/funciones.md
  #   - Clases: referencia/clases.md

# -------------------------------------------------------------
# DIRECTORIOS
# -------------------------------------------------------------
# Ruta de la carpeta que contiene todos los archivos .md (Markdown) de la documentación.
# MkDocs buscará aquí los archivos listados en 'nav'.
docs_dir: docs 
# -------------------------------------------------------------
# TEMA (Opcional, pero común)
# -------------------------------------------------------------
theme:
  name: material           # ← Esto es lo que hace que quede bonito
  palette:                 # Opcional: activa modo claro/oscuro automático
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro