# mkdocs.yml

# -------------------------------------------------------------
# CONFIGURACIÓN GENERAL DEL SITIO
# -------------------------------------------------------------
site_name: PPS-Unidad2-TareaRA2-Aguado-Hernandez-Naiara # Define el título que aparecerá en la barra de navegación y en la etiqueta <title> del navegador.

# -------------------------------------------------------------
# ESTRUCTURA DE NAVEGACIÓN (MENÚ)
# -------------------------------------------------------------
# Define la lista de enlaces y el orden de aparición en el menú de navegación principal.
nav:
  # El nombre de la sección en el menú: nombre_archivo.md
  - Inicio: index.md
  - Apartado 1 - Trazado de vulnerabilidad: TrazadoVulnerabilidadGoAnywhere.md   # o el nombre exacto que tengas
  - Apartado 2 - Análisis de vulnerabilidad: analisisVulnerabilidad.md
  - Apartado 3 - Comprobación requisitos: ComprobacionRequisitosAplicacion_naiara.md
  - Apartado 4 - Reflexión: reflexion.md# Se pueden añadir subsecciones anidando listas:
  # - Referencia: 
  #   - Funciones: referencia/funciones.md
  #   - Clases: referencia/clases.md

# -------------------------------------------------------------
# DIRECTORIOS
# -------------------------------------------------------------
# Ruta de la carpeta que contiene todos los archivos .md (Markdown) de la documentación.
# MkDocs buscará aquí los archivos listados en 'nav'.
docs_dir: docs 
# -------------------------------------------------------------
# TEMA (Opcional, pero común)
# -------------------------------------------------------------
# theme: 
#   name: 'material' # Si usas el popular tema Material for MkDocs.
#   # highlightjs: true
#   # code_fences: true